# Generated by Django 5.2.1 on 2026-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'User Data', 'verbose_name_plural': 'User Data'},
        ),
        migrations.AlterField(
            model_name='data',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='data',
            name='contact',
            field=models.CharField(max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='data',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
    ]
